/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import MVC.*;

/**
 *
 * @author manu2
 */
public class MainMenu extends javax.swing.JFrame {
   // private Character character = new Character();
    /**
     * Creates new form MainForm
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuJPanel = new javax.swing.JPanel();
        Fighting = new javax.swing.JButton();
        Training = new javax.swing.JButton();
        CheckStats = new javax.swing.JButton();
        mainMenuQuit = new javax.swing.JButton();
        mainRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(647, 552));

        MainMenuJPanel.setPreferredSize(new java.awt.Dimension(647, 552));

        Fighting.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Fighting.setText("Fighting");
        Fighting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FightingActionPerformed(evt);
            }
        });

        Training.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Training.setText("Training");
        Training.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainingActionPerformed(evt);
            }
        });

        CheckStats.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CheckStats.setText("Stats");
        CheckStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckStatsActionPerformed(evt);
            }
        });

        mainMenuQuit.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        mainMenuQuit.setText("Quit");
        mainMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuQuitActionPerformed(evt);
            }
        });

        mainRestart.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        mainRestart.setText("Restart");

        javax.swing.GroupLayout MainMenuJPanelLayout = new javax.swing.GroupLayout(MainMenuJPanel);
        MainMenuJPanel.setLayout(MainMenuJPanelLayout);
        MainMenuJPanelLayout.setHorizontalGroup(
            MainMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mainMenuQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainRestart)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuJPanelLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(MainMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fighting, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Training, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckStats, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(228, 228, 228))
        );
        MainMenuJPanelLayout.setVerticalGroup(
            MainMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuJPanelLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(Fighting, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Training, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(CheckStats, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addGroup(MainMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuQuit)
                    .addComponent(mainRestart))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuQuitActionPerformed
        Object source = evt.getSource();
        if (source == mainMenuQuit) {
            System.exit(0);
        }
    }//GEN-LAST:event_mainMenuQuitActionPerformed

    private void FightingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FightingActionPerformed
        Object source = evt.getSource();
         if(source == Fighting){
                SelectionMenu selectionMenu = new SelectionMenu();
                selectionMenu.setVisible(true);
                selectionMenu.pack();
                selectionMenu.setLocationRelativeTo(null);
                //selectionMenu.menu.setCharacter(character);
                this.hide();
        }
    }//GEN-LAST:event_FightingActionPerformed

    private void CheckStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckStatsActionPerformed
        Object source = evt.getSource();
         if(source == CheckStats){
                StatsMenu statsMenu = new StatsMenu();
                statsMenu.setVisible(true);
                statsMenu.pack();
                statsMenu.setLocationRelativeTo(null);
                //statsMenu.menu.setCharacter(character);
                //statsMenu.getEXP().setText(String.valueOf(character.getExp()));
               // statsMenu.getRank().setText(String.valueOf(character.getRank()));
                //statsMenu.getItems().setText(String.valueOf(character.items));
               // statsMenu.getClasses().setText(String.valueOf(character.getClasses().type));

                this.hide();
        }
    }//GEN-LAST:event_CheckStatsActionPerformed

    private void TrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainingActionPerformed
        Object source = evt.getSource();
        
        if(source == Training){
                TrainingMenu trainMenu = new TrainingMenu();
                trainMenu.setVisible(true);
                trainMenu.pack();
                trainMenu.setLocationRelativeTo(null);
                //trainMenu.menu.setCharacter(character);

                this.hide();
        }
    }//GEN-LAST:event_TrainingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckStats;
    private javax.swing.JButton Fighting;
    private javax.swing.JPanel MainMenuJPanel;
    private javax.swing.JButton Training;
    private javax.swing.JButton mainMenuQuit;
    private javax.swing.JButton mainRestart;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the character
     */
//    public Character getCharacter() {
//        return character;
//    }
//
//    /**
//     * @param character the character to set
//     */
//    public void setCharacter(Character character) {
//        this.character = character;
//    }
}
