/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import MVC.*;

/**
 *
 * @author manu2
 */
public class SelectionMenu extends javax.swing.JFrame {
    MainMenu menu = new MainMenu();
    /**
     * Creates new form SelectionMenu
     */
    public SelectionMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectionJPanel = new javax.swing.JPanel();
        easyBot = new javax.swing.JButton();
        moderateBot = new javax.swing.JButton();
        hardBot = new javax.swing.JButton();
        superHardBot = new javax.swing.JButton();
        bossBot = new javax.swing.JButton();
        selectionQuit = new javax.swing.JButton();
        selectionRestart = new javax.swing.JButton();
        selectionMenuBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectionJPanel.setPreferredSize(new java.awt.Dimension(647, 552));

        easyBot.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        easyBot.setText("Easy");
        easyBot.setPreferredSize(new java.awt.Dimension(43, 43));
        easyBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBotActionPerformed(evt);
            }
        });

        moderateBot.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        moderateBot.setText("Moderate");
        moderateBot.setPreferredSize(new java.awt.Dimension(43, 43));
        moderateBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moderateBotActionPerformed(evt);
            }
        });

        hardBot.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        hardBot.setText("Hard");
        hardBot.setPreferredSize(new java.awt.Dimension(43, 43));
        hardBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardBotActionPerformed(evt);
            }
        });

        superHardBot.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        superHardBot.setText("Superhard");
        superHardBot.setPreferredSize(new java.awt.Dimension(43, 43));
        superHardBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superHardBotActionPerformed(evt);
            }
        });

        bossBot.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bossBot.setText("Boss");
        bossBot.setPreferredSize(new java.awt.Dimension(43, 43));
        bossBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bossBotActionPerformed(evt);
            }
        });

        selectionQuit.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        selectionQuit.setText("Quit");
        selectionQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionQuitActionPerformed(evt);
            }
        });

        selectionRestart.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        selectionRestart.setText("Restart");
        selectionRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionRestartActionPerformed(evt);
            }
        });

        selectionMenuBack.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        selectionMenuBack.setText("Menu");
        selectionMenuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionMenuBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectionJPanelLayout = new javax.swing.GroupLayout(SelectionJPanel);
        SelectionJPanel.setLayout(SelectionJPanelLayout);
        SelectionJPanelLayout.setHorizontalGroup(
            SelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectionJPanelLayout.createSequentialGroup()
                        .addComponent(selectionQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectionRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SelectionJPanelLayout.createSequentialGroup()
                        .addComponent(selectionMenuBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectionJPanelLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(SelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hardBot, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superHardBot, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bossBot, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moderateBot, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(easyBot, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212))
        );
        SelectionJPanelLayout.setVerticalGroup(
            SelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectionMenuBack)
                .addGap(139, 139, 139)
                .addComponent(easyBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moderateBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(superHardBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bossBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(SelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectionQuit)
                    .addComponent(selectionRestart))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectionJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectionJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectionQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionQuitActionPerformed
        Object source = evt.getSource();
        if (source == selectionQuit) {
            System.exit(0);
        }
    }//GEN-LAST:event_selectionQuitActionPerformed

    private void easyBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBotActionPerformed
        Object source = evt.getSource();
         if(source == easyBot){
                
                Fighting fight = new Fighting();
                fight.setBotLevel(1);
                //fight.Player = menu.getCharacter();
                fight.fight();
                //FightingMenu fightMenu = new FightingMenu();
               // fightMenu.fight.setBotLevel(1);
               // fightMenu.setVisible(true);
                //fightMenu.pack();
               // fightMenu.setLocationRelativeTo(null);
                

                this.hide();
        }
    }//GEN-LAST:event_easyBotActionPerformed

    private void moderateBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moderateBotActionPerformed
        Object source = evt.getSource();
        if(source == moderateBot){
                
                FightingMenu fightMenu = new FightingMenu();
                fightMenu.setVisible(true);
                fightMenu.pack();
                fightMenu.setLocationRelativeTo(null);
                
                this.hide();
        }
        
    }//GEN-LAST:event_moderateBotActionPerformed

    private void hardBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardBotActionPerformed
        Object source = evt.getSource();
        if(source == hardBot){
                FightingMenu fightMenu = new FightingMenu();
                fightMenu.setVisible(true);
                fightMenu.pack();
                fightMenu.setLocationRelativeTo(null);
                
                this.hide();
        }
    }//GEN-LAST:event_hardBotActionPerformed

    private void superHardBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superHardBotActionPerformed
        // TODO add your handling code here:
        Object source = evt.getSource();
        if(source == superHardBot){
                FightingMenu fightMenu = new FightingMenu();
                fightMenu.setVisible(true);
                fightMenu.pack();
                fightMenu.setLocationRelativeTo(null);
               
                this.hide();
        }
    }//GEN-LAST:event_superHardBotActionPerformed

    private void bossBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bossBotActionPerformed
        // TODO add your handling code here:
        Object source = evt.getSource();
        if(source == bossBot){
                FightingMenu fightMenu = new FightingMenu();
                fightMenu.setVisible(true);
                fightMenu.pack();
                fightMenu.setLocationRelativeTo(null);
                
                this.hide();
        }
    }//GEN-LAST:event_bossBotActionPerformed

    private void selectionMenuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionMenuBackActionPerformed
        // TODO add your handling code here:

        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_selectionMenuBackActionPerformed

    private void selectionRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionRestartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectionRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SelectionJPanel;
    private javax.swing.JButton bossBot;
    private javax.swing.JButton easyBot;
    private javax.swing.JButton hardBot;
    private javax.swing.JButton moderateBot;
    private javax.swing.JButton selectionMenuBack;
    private javax.swing.JButton selectionQuit;
    private javax.swing.JButton selectionRestart;
    private javax.swing.JButton superHardBot;
    // End of variables declaration//GEN-END:variables

    
}
