/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import MVC.*;

/**
 *
 * @author manu2
 */
public class StatsMenu extends javax.swing.JFrame {

    //MainMenu menu = new MainMenu();

    /**
     * Creates new form Stats
     */
    public StatsMenu() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatsJPanel = new javax.swing.JPanel();
        classes = new javax.swing.JLabel();
        ItemLabel = new javax.swing.JLabel();
        Items = new javax.swing.JLabel();
        EXP = new javax.swing.JLabel();
        ExpLabel = new javax.swing.JLabel();
        RankLabel1 = new javax.swing.JLabel();
        Rank = new javax.swing.JLabel();
        StatsLabel = new javax.swing.JLabel();
        menuBackStats = new javax.swing.JButton();
        statsQuit = new javax.swing.JButton();
        statsRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 400));

        StatsJPanel.setPreferredSize(new java.awt.Dimension(647, 552));

        classes.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        ItemLabel.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        ItemLabel.setText("Items:");

        Items.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N

        EXP.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N

        ExpLabel.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        ExpLabel.setText("EXP:");

        RankLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        RankLabel1.setText("Rank:");

        Rank.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N

        StatsLabel.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        StatsLabel.setText("Stats");

        menuBackStats.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        menuBackStats.setText("Menu");
        menuBackStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBackStatsActionPerformed(evt);
            }
        });

        statsQuit.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        statsQuit.setText("Quit");
        statsQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsQuitActionPerformed(evt);
            }
        });

        statsRestart.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        statsRestart.setText("Restart");

        javax.swing.GroupLayout StatsJPanelLayout = new javax.swing.GroupLayout(StatsJPanel);
        StatsJPanel.setLayout(StatsJPanelLayout);
        StatsJPanelLayout.setHorizontalGroup(
            StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatsJPanelLayout.createSequentialGroup()
                        .addComponent(menuBackStats, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(StatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(319, 319, 319))
                    .addGroup(StatsJPanelLayout.createSequentialGroup()
                        .addComponent(statsQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statsRestart)
                        .addContainerGap())))
            .addGroup(StatsJPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatsJPanelLayout.createSequentialGroup()
                        .addComponent(ItemLabel)
                        .addGap(56, 56, 56)
                        .addComponent(Items)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(StatsJPanelLayout.createSequentialGroup()
                        .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StatsJPanelLayout.createSequentialGroup()
                                .addComponent(ExpLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EXP))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StatsJPanelLayout.createSequentialGroup()
                                .addComponent(RankLabel1)
                                .addGap(59, 59, 59)
                                .addComponent(Rank)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(classes)
                        .addGap(76, 76, 76))))
        );
        StatsJPanelLayout.setVerticalGroup(
            StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsJPanelLayout.createSequentialGroup()
                .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatsJPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(StatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StatsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuBackStats)))
                .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatsJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RankLabel1)
                            .addComponent(Rank))
                        .addGap(67, 67, 67))
                    .addGroup(StatsJPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(classes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)))
                .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpLabel)
                    .addComponent(EXP))
                .addGap(71, 71, 71)
                .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemLabel)
                    .addComponent(Items))
                .addGap(59, 59, 59)
                .addGroup(StatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsQuit)
                    .addComponent(statsRestart))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StatsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StatsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statsQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsQuitActionPerformed
        Object source = evt.getSource();
        if (source == statsQuit) {
            System.exit(0);
        }
    }//GEN-LAST:event_statsQuitActionPerformed

    private void menuBackStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBackStatsActionPerformed
        // TODO add your handling code here:

        Object source = evt.getSource();
        if (source == menuBackStats) {

            //menu.setVisible(true);
            //menu.pack();
            //menu.setLocationRelativeTo(null);
            this.hide();

        }
    }//GEN-LAST:event_menuBackStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new StatsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EXP;
    private javax.swing.JLabel ExpLabel;
    private javax.swing.JLabel ItemLabel;
    private javax.swing.JLabel Items;
    private javax.swing.JLabel Rank;
    private javax.swing.JLabel RankLabel1;
    private javax.swing.JPanel StatsJPanel;
    private javax.swing.JLabel StatsLabel;
    private javax.swing.JLabel classes;
    private javax.swing.JButton menuBackStats;
    private javax.swing.JButton statsQuit;
    private javax.swing.JButton statsRestart;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the EXP
     */
    public javax.swing.JLabel getEXP() {
        return EXP;
    }

    /**
     * @param EXP the EXP to set
     */
    public void setEXP(javax.swing.JLabel EXP) {
        this.EXP = EXP;
    }

    /**
     * @return the Items
     */
    public javax.swing.JLabel getItems() {
        return Items;
    }

    /**
     * @param Items the Items to set
     */
    public void setItems(javax.swing.JLabel Items) {
        this.Items = Items;
    }

    /**
     * @return the Rank
     */
    public javax.swing.JLabel getRank() {
        return Rank;
    }

    /**
     * @param Rank the Rank to set
     */
    public void setRank(javax.swing.JLabel Rank) {
        this.Rank = Rank;
    }

    /**
     * @return the classes
     */
    public javax.swing.JLabel getClasses() {
        return classes;
    }

    /**
     * @param classes the classes to set
     */
    public void setClasses(javax.swing.JLabel classes) {
        this.classes = classes;
    }
}
