/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import MVC.*;
import javax.swing.JOptionPane;

/**
 *
 * @author manu2
 */
public class TrainingMenu extends javax.swing.JFrame {
    private final int trainingNumber = 10;
    MainMenu menu = new MainMenu();
    Training train = new Training(trainingNumber);
    /**
     * Creates new form Training
     */
    public TrainingMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrainingJPanel = new javax.swing.JPanel();
        TrainingLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        trainingQuit = new javax.swing.JButton();
        trainingExpLabel = new javax.swing.JLabel();
        trainingExp = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        trainingMenuBack = new javax.swing.JButton();
        trainingRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(647, 552));

        TrainingJPanel.setPreferredSize(new java.awt.Dimension(647, 552));

        TrainingLabel.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        TrainingLabel.setText("Training");

        startButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        trainingQuit.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        trainingQuit.setText("Quit");
        trainingQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingQuitActionPerformed(evt);
            }
        });

        trainingExpLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        trainingExpLabel.setText("Exp");

        trainingExp.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        trainingExp.setText("");

        updateButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        trainingMenuBack.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        trainingMenuBack.setText("Menu");
        trainingMenuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingMenuBackActionPerformed(evt);
            }
        });

        trainingRestart.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        trainingRestart.setText("Restart");
        trainingRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TrainingJPanelLayout = new javax.swing.GroupLayout(TrainingJPanel);
        TrainingJPanel.setLayout(TrainingJPanelLayout);
        TrainingJPanelLayout.setHorizontalGroup(
            TrainingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainingJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrainingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainingQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TrainingJPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(trainingMenuBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(trainingRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(TrainingJPanelLayout.createSequentialGroup()
                .addGroup(TrainingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrainingJPanelLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(TrainingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrainingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TrainingJPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(TrainingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(trainingExp)
                                    .addGroup(TrainingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(TrainingJPanelLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(trainingExpLabel)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        TrainingJPanelLayout.setVerticalGroup(
            TrainingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainingJPanelLayout.createSequentialGroup()
                .addComponent(trainingMenuBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TrainingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(startButton)
                .addGap(46, 46, 46)
                .addComponent(updateButton)
                .addGap(29, 29, 29)
                .addComponent(trainingExpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trainingExp)
                .addGap(42, 42, 42)
                .addGroup(TrainingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainingQuit)
                    .addComponent(trainingRestart)))
        );

        updateButton.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TrainingJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrainingJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        Object source = evt.getSource();
        if(source == startButton)
        {
            startButton.setVisible(false);   
            JOptionPane.showMessageDialog(rootPane, "Training Started", "Training", 2);
            Thread thread = new Thread(train);
            thread.start();        
            try {
                thread.sleep(10000);

            } catch (InterruptedException ex) {
                System.out.println("The sleeping has been interruped!");
            }
            
            train.trainPlayer();                      
        }     
        updateButton.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void trainingQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingQuitActionPerformed
        Object source = evt.getSource();
        if (source == trainingQuit) {
            System.exit(0);
        }
    }//GEN-LAST:event_trainingQuitActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        Object source = evt.getSource();
        if(source == updateButton)
        {
            //menu.getCharacter().setExp(menu.getCharacter().getExp() + train.getExp());
            trainingExp.setText(String.valueOf(train.getExp()));
            startButton.setVisible(true); 
        }
        updateButton.setVisible(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void trainingMenuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingMenuBackActionPerformed
        // TODO add your handling code here:
 
        menu.setVisible(true);
        menu.pack();
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_trainingMenuBackActionPerformed

    private void trainingRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingRestartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainingRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainingMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TrainingJPanel;
    private javax.swing.JLabel TrainingLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel trainingExp;
    private javax.swing.JLabel trainingExpLabel;
    private javax.swing.JButton trainingMenuBack;
    private javax.swing.JButton trainingQuit;
    private javax.swing.JButton trainingRestart;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
