/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC;



/**
 *
 * @author manu2
 */
public class FightingMenu extends javax.swing.JFrame {

    private int attackType;
    
    /**
     * Creates new form Fighting
     */
    public FightingMenu() {
        initComponents();
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Attack1 = new javax.swing.JButton();
        Attack2 = new javax.swing.JButton();
        Attack3 = new javax.swing.JButton();
        Attack4 = new javax.swing.JButton();
        fightingQuit = new javax.swing.JButton();
        Health = new javax.swing.JLabel();
        botHealth = new javax.swing.JLabel();
        fightingMenuBack = new javax.swing.JButton();
        fightingRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Attack1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        Attack1.setText("Attack1");
        Attack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attack1ActionPerformed(evt);
            }
        });

        Attack2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        Attack2.setText("Attack2");
        Attack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attack2ActionPerformed(evt);
            }
        });

        Attack3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        Attack3.setText("Attack3");
        Attack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attack3ActionPerformed(evt);
            }
        });

        Attack4.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        Attack4.setText("Attack4");
        Attack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attack4ActionPerformed(evt);
            }
        });

        fightingQuit.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        fightingQuit.setText("Quit");
        fightingQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightingQuitActionPerformed(evt);
            }
        });

        Health.setText("jLabel1");

        botHealth.setText("jLabel1");

        fightingMenuBack.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        fightingMenuBack.setText("Menu");
        fightingMenuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightingMenuBackActionPerformed(evt);
            }
        });

        fightingRestart.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        fightingRestart.setText("Restart");
        fightingRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightingRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fightingRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(Attack1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fightingQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fightingMenuBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Attack3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Attack2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Attack4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Health)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botHealth)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Health)
                    .addComponent(botHealth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Attack1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Attack2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Attack4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Attack3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fightingRestart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fightingMenuBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fightingQuit)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fightingQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightingQuitActionPerformed
        Object source = evt.getSource();
        if (source == getFightingQuit()) {
            System.exit(0);
        }
    }//GEN-LAST:event_fightingQuitActionPerformed

    private void Attack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attack2ActionPerformed
      
    }//GEN-LAST:event_Attack2ActionPerformed

    private void Attack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attack1ActionPerformed
        
    }//GEN-LAST:event_Attack1ActionPerformed

    private void Attack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attack3ActionPerformed
        
    }//GEN-LAST:event_Attack3ActionPerformed

    private void Attack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attack4ActionPerformed
       
    }//GEN-LAST:event_Attack4ActionPerformed

    private void fightingMenuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightingMenuBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fightingMenuBackActionPerformed

    private void fightingRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightingRestartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fightingRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FightingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FightingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FightingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FightingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FightingMenu().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attack1;
    private javax.swing.JButton Attack2;
    private javax.swing.JButton Attack3;
    private javax.swing.JButton Attack4;
    private javax.swing.JLabel Health;
    private javax.swing.JLabel botHealth;
    private javax.swing.JButton fightingMenuBack;
    private javax.swing.JButton fightingQuit;
    private javax.swing.JButton fightingRestart;
    // End of variables declaration//GEN-END:variables
    
    /**
     * @return the Attack1
     */
    public javax.swing.JButton getAttack1() {
        return Attack1;
    }

    /**
     * @param Attack1 the Attack1 to set
     */
    public void setAttack1(javax.swing.JButton Attack1) {
        this.Attack1 = Attack1;
    }

    /**
     * @return the Attack2
     */
    public javax.swing.JButton getAttack2() {
        return Attack2;
    }

    /**
     * @param Attack2 the Attack2 to set
     */
    public void setAttack2(javax.swing.JButton Attack2) {
        this.Attack2 = Attack2;
    }

    /**
     * @return the Attack3
     */
    public javax.swing.JButton getAttack3() {
        return Attack3;
    }

    /**
     * @param Attack3 the Attack3 to set
     */
    public void setAttack3(javax.swing.JButton Attack3) {
        this.Attack3 = Attack3;
    }

    /**
     * @return the Attack4
     */
    public javax.swing.JButton getAttack4() {
        return Attack4;
    }

    /**
     * @param Attack4 the Attack4 to set
     */
    public void setAttack4(javax.swing.JButton Attack4) {
        this.Attack4 = Attack4;
    }

    /**
     * @return the Health
     */
    public javax.swing.JLabel getHealth() {
        return Health;
    }

    /**
     * @param Health the Health to set
     */
    public void setHealth(javax.swing.JLabel Health) {
        this.Health = Health;
    }

    /**
     * @return the attackType
     */
    public int getAttackType() {
        return attackType;
    }

    /**
     * @param attackType the attackType to set
     */
    public void setAttackType(int attackType) {
        this.attackType = attackType;
    }

    /**
     * @return the botHealth
     */
    public javax.swing.JLabel getBotHealth() {
        return botHealth;
    }

    /**
     * @param botHealth the botHealth to set
     */
    public void setBotHealth(javax.swing.JLabel botHealth) {
        this.botHealth = botHealth;
    }

    /**
     * @return the fightingMenuBack
     */
    public javax.swing.JButton getFightingMenuBack() {
        return fightingMenuBack;
    }

    /**
     * @param fightingMenuBack the fightingMenuBack to set
     */
    public void setFightingMenuBack(javax.swing.JButton fightingMenuBack) {
        this.fightingMenuBack = fightingMenuBack;
    }

    /**
     * @return the fightingQuit
     */
    public javax.swing.JButton getFightingQuit() {
        return fightingQuit;
    }

    /**
     * @param fightingQuit the fightingQuit to set
     */
    public void setFightingQuit(javax.swing.JButton fightingQuit) {
        this.fightingQuit = fightingQuit;
    }

    /**
     * @return the fightingRestart
     */
    public javax.swing.JButton getFightingRestart() {
        return fightingRestart;
    }

    /**
     * @param fightingRestart the fightingRestart to set
     */
    public void setFightingRestart(javax.swing.JButton fightingRestart) {
        this.fightingRestart = fightingRestart;
    }
}
